### ISSUE TITLE
What happened to emails on January 12th?

### ISSUE THREAD

**Issue by chrishunt** [codecation/trailmix#144]
Sendgrid deliverability was not good on January 12th. The [status blog](http://status.sendgrid.com/) shows no interruptions. Some folks did not get their daily email.

If I look back to August 1st 2014, this has never happened before and it has not happened since.

Any ideas?

![screen shot 2015-01-18 at 3 58 53 pm](https://cloud.githubusercontent.com/assets/65323/5794608/07eda8b6-9f2b-11e4-94c9-c12337e9ae9f.png)

**Comment by r00k** [comment]
Nothing comes to mind. I suppose we'll just have to keep our eyes on this.
