### ISSUE TITLE
Update to Heroku Cedar-14 stack

### ISSUE THREAD

**Issue by chrishunt** [codecation/trailmix#150]
When last deploying Trailmix, I was given the following warning:

> Cedar-10 will reach end-of-life on November 4th, 2015.
> Upgrade to Cedar-14 at your earliest convenience.
> For more information, check out the following Dev Center article:
> https://devcenter.heroku.com/articles/cedar-14-migration

**Comment by chrishunt** [comment]
This is done. :tada:

<img width="470" alt="screen shot 2015-06-17 at 7 55 54 am" src="https://cloud.githubusercontent.com/assets/65323/8210319/532faaa2-14c6-11e5-8269-f5a4b49825e0.png">

<img width="492" alt="screen shot 2015-06-17 at 7 55 26 am" src="https://cloud.githubusercontent.com/assets/65323/8210323/56a565f0-14c6-11e5-98a7-87e7b094aad7.png">

**Comment by r00k** [comment]
Yay!

On Wednesday, June 17, 2015, Chris Hunt <notifications@github.com> wrote:

> Closed #150 <https://github.com/codecation/trailmix/issues/150>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codecation/trailmix/issues/150#event-333261019>.
>


-- 
-Ben
