### ISSUE TITLE
Email onboarding ideas

### ISSUE THREAD

**Issue by r00k** [codecation/trailmix#8]
This is how OhLife does it.

## First prompt

How's your day going? Just reply to this email with your answer, and it's
instantly saved in your OhLife account. Try it!

Helpful tips:

1. It's okay to keep it simple! Even one sentence about how your day is going
is just fine.

2. Only you can read what you write. That means there's no wrong way to do
this.

3. So long as you write something, you did a great job.

## After responding to first prompt

Congrats on writing your first entry!

We're here to help you remember what's happened in your life - now that you've
written your first entry, you're well on your way. That's something to feel
good about!

You can check out your entry here: https://ohlife.com/latest

P.S. You'll get your next email tomorrow

## After responding to second prompt

What have you been up to on this fine Thursday? Just reply to this email with
your entry.

After you've used OhLife for a week, we'll start showing you exactly what you
did one week ago. Later on we'll start showing you entries from a month ago. So
keep at it!

## After a few days

Tip: Even if today seems like just a regular day, you'll enjoy reading about it in the future.

**Comment by graysonwright** [comment]
Hey, Ben.

I'm giving Trailmix a try, and it looks like I got two emails on the first day – on immediately after signing up, and then one on the daily scheduled time for the first day.

Enjoying the app so far, keep it up!

**Comment by r00k** [comment]
Thanks for the report!

Glad you're liking the app.

On Monday, January 5, 2015, Grayson Wright <notifications@github.com> wrote:

> Hey, Ben.
>
> I'm giving Trailmix a try, and it looks like I got two emails on the first
> day – on immediately after signing up, and then one on the daily scheduled
> time for the first day.
>
> Enjoying the app so far, keep it up!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codecation/trailmix/issues/8#issuecomment-68826435>.
>


-- 
-Ben

**Comment by r00k** [comment]
Sure. It's a good idea, but it's not an issue. Closing.
